<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/25 0025
 * Time: 下午 3:02
 */
namespace app\seller\controller;

class Order extends Base
{

    private $Source;
    private $AssociatedAs;
    private $sid;

    protected function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Source = model('Source');
        $this->AssociatedAs = model('AssociatedAs');
        $this->sid = session('userInfo.store');
    }

    //订单首页
    public function index(){
        $source = $this->Source->select();
        $activityInfo = $this->AssociatedAs->getSellerActivityIndexList($this->sid);
        $pay_way = config('PAY_WAY');

        return $this->fetch('',[
            'source' => $source,
            'activityInfo' => $activityInfo,
            'pay_way' => $pay_way
        ]);
    }

    //ajax订单首页
    public function ajax_activity_order(){
        $data = input('get.');

        $where = array();

        $data['aid'] == 0 ? $where['o.aid'] = array('>',0) : $where['o.aid'] = $data['aid'];
        $data['begin_time'] != '' ? $where['o.addtime'] = array('between',[strtotime($data['begin_time']),strtotime($data['end_time'])+3600*12]) : false;
        $data['pay_way'] != '' ? $where['o.pay_way'] = $data['pay_way'] : false;
        $data['order_status'] != '' ? $where['o.order_status'] = $data['order_status'] : false;
        $data['source'] != '' ? $where['o.source'] = $data['source'] : false;

        //输入框输入姓名或手机号
        if($data['text'] != ''){
            if(isMobile($data['text'])){
                $where['o.mobile'] = $data['text'];
            }else{
                $where['o.name'] = $data['text'];
            }
        }

        //查询已付款的订单，需要连同未签到的数据一起查出
        if($data['order_status'] != ''){
            if( $data['order_status'] == 3){
                $where['o.order_status'] = array(['=',3],['=',4],'or');
            }else{
                $where['o.order_status'] = $data['order_status'];
            }
        }

        //固定条件
        $where2 = [
            'order_status' => array('neq',2),
            'store' => $this->sid
        ];

        $orderInfo = model('ActivityOrder')
            ->alias('o')->field('o.*,a.a_title,s.name as source_name,t.begin_time,t.end_time')
            ->join('mfw_activity a','o.aid=a.aid','left')
            ->join('mfw_activity_time t','t.t_id=o.t_id','left')
            ->join('mfw_source s','o.source=s.id','left')
            ->where($where)
            ->where($where2)
            ->order('o.order_id desc')
            ->paginate(10);

        $price_sum = model('ActivityOrder')
            ->alias('o')->field('o.*,a.a_title,s.name as source_name,t.begin_time,t.end_time')
            ->join('mfw_activity a','o.aid=a.aid','left')
            ->join('mfw_activity_time t','t.t_id=o.t_id','left')
            ->join('mfw_source s','o.source=s.id','left')
            ->where($where)
            ->where($where2)
            ->order('o.order_id desc')
            ->sum('o.order_price');

        $page = $orderInfo->render();

        return $this->fetch('',[
            'orderInfo' => $orderInfo,
            'page' => $page,
            'price_sum' => $price_sum
        ]);
    }

    //显示添加订单界面
    public function dis_add_order(){
        return $this->fetch();
    }
}